export type Availability = "Immediate" | "2 weeks" | "1 month" | "3 months";
export type EmploymentType = "Full-time" | "Contract" | "Part-time";
export type RoleCategory =
  | "software_engineering"
  | "mobile_development"
  | "web_development"
  | "vibe_coding"
  | "product_management"
  | "design_ux"
  | "data_analytics"
  | "ai_ml"
  | "devops_infrastructure"
  | "cybersecurity"
  | "marketing";

export interface TalentProfile {
  id: string;
  name: string;
  headline: string;
  bio: string;
  location: string;
  country: string;
  profilePhotoUrl: string;
  coverMediaUrl?: string;
  sectors: string[];
  primarySkills: string[];
  secondarySkills: string[];
  yearsOfExperience: number;
  availability: Availability;
  employmentType: EmploymentType[];
  compensationMin: number;
  compensationMax: number;
  portfolioLinks: {
    github?: string;
    linkedin?: string;
    dribbble?: string;
    portfolio?: string;
    twitter?: string;
  };
  resumeUrl?: string;
  featured: boolean;
}

export type { TalentProfile as TalentProfileLegacy };

export const mockTalent: TalentProfile[] = [
  {
    id: "michael-okpechi",
    name: "Michael Chibuikem Okpechi",
    headline: "Mobile Developer · Flutter, Swift & Kotlin",
    bio: "For me, mobile development isn't just a career, it's a brand. I'm fully embracing the current wave of AI as a tool to elevate mobile experiences and ship products that feel smarter, faster, and more human. I graduated in the top 1% of my university with a First Class in Computer Science in 2024. In one year I've worked with companies across Nigeria, Germany, Canada, and Singapore.",
    location: "Lagos, Nigeria",
    country: "Nigeria",
    profilePhotoUrl: "https://res.cloudinary.com/dwwzrtzb8/image/upload/v1754338062/IMG_4411_okdfur.jpg",
    coverMediaUrl: "https://res.cloudinary.com/dwwzrtzb8/image/upload/v1754338917/okpechi_michael_ihhvbc.jpg",
    sectors: ["mobile_development", "software_engineering"],
    primarySkills: ["Flutter", "Swift", "Kotlin", "Dart"],
    secondarySkills: ["iOS", "Android", "Firebase", "REST APIs"],
    yearsOfExperience: 4,
    availability: "2 weeks",
    employmentType: ["Full-time", "Contract"],
    compensationMin: 1200,
    compensationMax: 2000,
    portfolioLinks: {
      github: "https://github.com/mik3yyy",
      linkedin: "https://www.linkedin.com/in/chibuikem-michael-okpechi/",
    },
    resumeUrl: "https://firebasestorage.googleapis.com/v0/b/mikeokpechi-e4331.firebasestorage.app/o/resumes%2FMichael-Okpechi-FlowCV-UK.pdf?alt=media&token=2117f920-edb3-4a6d-b6fb-270b1b8e0a32",
    featured: true,
  },
  {
    id: "ebong-nsikak-abasi",
    name: "Ebong Nsikak-Abasi Nseyen",
    headline: "Fullstack Developer · AI, Cloud & Data Engineering",
    bio: "First Class Computer Science graduate with 3+ years of experience in full stack development, data science, cloud computing, and AI engineering. I build scalable, intelligent, and user-focused applications combining modern frontend and backend technologies with data-driven insights and cloud-native architectures.",
    location: "Uyo, Nigeria",
    country: "Nigeria",
    profilePhotoUrl: "https://res.cloudinary.com/dwwzrtzb8/image/upload/v1754241298/profile_images/_MG_9288.jpeg.jpg",
    coverMediaUrl: "https://res.cloudinary.com/dwwzrtzb8/image/upload/v1755649009/profile_images/IMG_4641.jpeg.jpg",
    sectors: ["software_engineering", "ai_ml", "data_analytics"],
    primarySkills: ["Python", "Django", "React", "TypeScript"],
    secondarySkills: ["NestJS", "PostgreSQL", "MongoDB", "AWS", "Docker", "Machine Learning", "NLP"],
    yearsOfExperience: 3,
    availability: "2 weeks",
    employmentType: ["Full-time", "Contract"],
    compensationMin: 900,
    compensationMax: 1500,
    portfolioLinks: {
      github: "https://github.com/Nsiikak",
      linkedin: "https://www.linkedin.com/in/nsikak-abasi-ebong98",
    },
    resumeUrl: "https://firebasestorage.googleapis.com/v0/b/mikeokpechi-e4331.firebasestorage.app/o/resumes%2F1755650489623_Nsikak-Ebong's%20Resume.pdf?alt=media&token=539f036c-ec52-44e7-a8fb-732fabd81d84",
    featured: true,
  },
  {
    id: "asoegwu-stephanie",
    name: "Asoegwu Stephanie",
    headline: "UI/UX Designer · Figma, Framer & No-Code Expert",
    bio: "UI/UX designer focused on creating clean, easy-to-use designs for web and mobile products. I've worked on apps in AI, EdTech, and SaaS — turning wireframes into smooth, user-friendly interfaces. I recently graduated with First Class Honours in Information Technology, and I've designed features used across Nigeria, the UK, the US, Australia, and more.",
    location: "Lagos, Nigeria",
    country: "Nigeria",
    profilePhotoUrl: "https://res.cloudinary.com/dwwzrtzb8/image/upload/v1754330391/profile_images/IMG_3921.jpeg.jpg",
    coverMediaUrl: "https://res.cloudinary.com/dwwzrtzb8/image/upload/v1754330493/profile_images/IMG_3489.jpeg.jpg",
    sectors: ["design_ux", "web_development"],
    primarySkills: ["Figma", "Framer", "UX Design", "Prototyping"],
    secondarySkills: ["Canva", "Design Systems", "Wireframing", "A/B Testing", "HTML/CSS", "Usability Testing"],
    yearsOfExperience: 3,
    availability: "2 weeks",
    employmentType: ["Full-time", "Contract"],
    compensationMin: 800,
    compensationMax: 1300,
    portfolioLinks: {
      dribbble: "https://dribbble.com/crownzdesigns",
      linkedin: "https://www.linkedin.com/in/stephanie-asoegwu",
    },
    resumeUrl: "https://firebasestorage.googleapis.com/v0/b/mikeokpechi-e4331.firebasestorage.app/o/resumes%2F1754328704818_Stephanie-Asoegwu-CV-compressed.pdf?alt=media&token=b65a2d20-1cf0-4d86-8fff-d732e26018b1",
    featured: true,
  },
  {
    id: "emelifonwu-william",
    name: "Emelifonwu William",
    headline: "Frontend Engineer · React, Next.js & TypeScript",
    bio: "Frontend developer with over 3 years of experience building responsive, user-friendly web apps with React, Next.js, TypeScript, and Tailwind CSS. I really enjoy turning ideas into clean, functional interfaces and working with teams to bring products to life.",
    location: "Lagos, Nigeria",
    country: "Nigeria",
    profilePhotoUrl: "https://res.cloudinary.com/dwwzrtzb8/image/upload/v1754309148/profile_images/JV0A6119.jpg.jpg",
    coverMediaUrl: "https://res.cloudinary.com/dwwzrtzb8/image/upload/v1754333692/profile_images/william.jpg.jpg",
    sectors: ["web_development", "software_engineering"],
    primarySkills: ["React", "Next.js", "TypeScript", "Tailwind CSS"],
    secondarySkills: ["JavaScript", "REST APIs", "Cypress", "WebSockets", "SEO"],
    yearsOfExperience: 3,
    availability: "2 weeks",
    employmentType: ["Full-time", "Contract"],
    compensationMin: 800,
    compensationMax: 1300,
    portfolioLinks: {
      github: "https://github.com/westliam-x",
      linkedin: "https://www.linkedin.com/in/william-emelifonwu/",
    },
    resumeUrl: "https://firebasestorage.googleapis.com/v0/b/mikeokpechi-e4331.firebasestorage.app/o/resumes%2F1754332111769_Emelifonwu-William-Resume.pdf?alt=media&token=8dc907b9-07d3-483f-b3de-ce25403b6e60",
    featured: false,
  },
  {
    id: "ikeaba-tochukwu-adrian",
    name: "Ikeaba Tochukwu Adrian",
    headline: "Mobile Engineer · Kotlin, Swift & Spring Boot",
    bio: "Experienced Mobile and backend engineer with over 5 years helping companies bring their tech ideas to life. Master of crafting seamless, stable mobile apps on Kotlin and strong backend systems on Java and Spring Boot. I've worked with startups and growing companies across several sectors, counseling solo and team projects from inception to completion.",
    location: "Lagos, Nigeria",
    country: "Nigeria",
    profilePhotoUrl: "https://res.cloudinary.com/dwwzrtzb8/image/upload/v1754306013/profile_images/Ikeaba%20Adrian.jpeg.jpg",
    coverMediaUrl: "https://res.cloudinary.com/dwwzrtzb8/image/upload/v1754345827/profile_images/WhatsApp%20Image%202025-08-04%20at%209.26.05%E2%80%AFPM.jpeg.jpg",
    sectors: ["mobile_development", "software_engineering"],
    primarySkills: ["Kotlin", "Swift", "Java", "Android"],
    secondarySkills: ["iOS", "Spring Boot", "Clean Architecture", "REST APIs"],
    yearsOfExperience: 6,
    availability: "2 weeks",
    employmentType: ["Full-time", "Contract"],
    compensationMin: 1500,
    compensationMax: 2200,
    portfolioLinks: {
      github: "https://github.com/AdrianIkeaba/",
      linkedin: "https://www.linkedin.com/in/adrian-ikeaba-893200222/",
    },
    resumeUrl: "https://firebasestorage.googleapis.com/v0/b/mikeokpechi-e4331.firebasestorage.app/o/resumes%2F1754337794495_Ikeaba_Adrian_Android_Engineer_Resume.pdf?alt=media&token=02d61731-f12b-4843-80aa-81424ecd89e1",
    featured: true,
  },
  {
    id: "shepherd-umanah",
    name: "Shepherd Umanah",
    headline: "Backend Engineer · C#, PHP, Python & ASP.NET",
    bio: "Passionate and results-driven Software Engineer with 4 years of professional experience building scalable, secure, and high-performance backend systems. I specialize in clean and maintainable APIs, leading cross-functional teams, and delivering reliable solutions that power both startups and enterprise platforms.",
    location: "Abuja, Nigeria",
    country: "Nigeria",
    profilePhotoUrl: "https://res.cloudinary.com/dwwzrtzb8/image/upload/v1754241706/profile_images/imglink.jpeg.jpg",
    sectors: ["software_engineering"],
    primarySkills: ["C#", "PHP", "Python", "ASP.NET Core"],
    secondarySkills: ["Laravel", "FastAPI", "Node.js", "TypeScript", "Docker", "AWS", "MySQL"],
    yearsOfExperience: 4,
    availability: "2 weeks",
    employmentType: ["Full-time", "Contract"],
    compensationMin: 1100,
    compensationMax: 1700,
    portfolioLinks: {
      github: "https://github.com/shepherrrd",
      linkedin: "https://www.linkedin.com/in/shepherd-umanah-805652254/",
    },
    resumeUrl: "https://firebasestorage.googleapis.com/v0/b/mikeokpechi-e4331.firebasestorage.app/o/resumes%2F1754241296343_Shepherd%20Umanah%20Resume%20(1).pdf?alt=media&token=d66c7e5c-f33a-4179-ae20-ada94ab74474",
    featured: true,
  },
  {
    id: "samuel-abolo",
    name: "Samuel Abolo",
    headline: "Backend & ML Engineer · Python, Go & Distributed Systems",
    bio: "Software engineer passionate about building scalable backend systems, reliable infrastructure, and tools that make life easier for developers. I work at the intersection of machine learning, distributed systems, and backend engineering, focusing on clean architectures, improved system performance, and solving real-world problems.",
    location: "Lagos, Nigeria",
    country: "Nigeria",
    profilePhotoUrl: "https://res.cloudinary.com/dwwzrtzb8/image/upload/v1754255973/profile_images/Screenshot%202025-08-03%20at%2022.19.02.png.png",
    sectors: ["software_engineering", "ai_ml", "devops_infrastructure"],
    primarySkills: ["Python", "FastAPI", "Django", "JavaScript"],
    secondarySkills: ["React", "React Native", "PostgreSQL", "Redis", "Kafka", "Kubernetes", "Docker", "AWS", "Terraform"],
    yearsOfExperience: 4,
    availability: "2 weeks",
    employmentType: ["Full-time", "Contract"],
    compensationMin: 1100,
    compensationMax: 1800,
    portfolioLinks: {
      github: "https://github.com/tecnosam",
      linkedin: "https://www.linkedin.com/in/samuel-abolo-24431a176/",
    },
    resumeUrl: "https://firebasestorage.googleapis.com/v0/b/mikeokpechi-e4331.firebasestorage.app/o/resumes%2F1754255761101_Samuel-Abolo-Resume.pdf?alt=media&token=59b0d98e-78cc-418c-b267-ab00283b8832",
    featured: true,
  },
  {
    id: "uchenna-ngozi",
    name: "Uchenna Ngozi",
    headline: "Backend Engineer · Python, Go, Rust & Distributed Systems",
    bio: "Software Engineer with a strong focus on backend development and deep expertise in Python, complemented by experience across C, C++, Go, and Rust. Skilled in designing, building, and deploying scalable systems with a solid foundation in database engineering, distributed architectures, and DevOps practices.",
    location: "Lagos, Nigeria",
    country: "Nigeria",
    profilePhotoUrl: "https://res.cloudinary.com/dwwzrtzb8/image/upload/v1755028879/profile_images/IMG_20240904_081915_499.jpg.jpg",
    sectors: ["software_engineering", "devops_infrastructure"],
    primarySkills: ["Python", "Go", "Rust", "Django"],
    secondarySkills: ["FastAPI", "TypeScript", "PostgreSQL", "MySQL", "Redis", "Docker", "AWS", "GCP"],
    yearsOfExperience: 3,
    availability: "2 weeks",
    employmentType: ["Full-time"],
    compensationMin: 900,
    compensationMax: 1600,
    portfolioLinks: {
      github: "https://github.com/justuchena",
      linkedin: "https://www.linkedin.com/in/uchenna-ngozi/",
    },
    resumeUrl: "https://firebasestorage.googleapis.com/v0/b/mikeokpechi-e4331.firebasestorage.app/o/resumes%2F1755033056634_Uchenna-Ngozi-CV%20(4).pdf?alt=media&token=836ee9c2-ff4c-410a-a126-5144bb1e244d",
    featured: true,
  },
  {
    id: "okpara-chinemerem-delight",
    name: "Okpara Chinemerem Delight",
    headline: "Full-Stack Developer · React, Next.js, Django & GraphQL",
    bio: "Full-Stack Developer with strong experience building scalable, performant web applications using React, Next.js, Django, and GraphQL. Proficient in crafting secure backends and seamless UIs, integrating Figma designs into responsive frontends with Tailwind CSS. Adept at working in remote teams using GitHub and CI/CD pipelines.",
    location: "Lagos, Nigeria",
    country: "Nigeria",
    profilePhotoUrl: "https://res.cloudinary.com/dwwzrtzb8/image/upload/v1754303214/profile_images/Screenshot%202025-08-04%20at%2011.26.12%20AM.png.png",
    sectors: ["software_engineering", "web_development"],
    primarySkills: ["React.js", "Next.js", "Django", "GraphQL"],
    secondarySkills: ["TypeScript", "PostgreSQL", "MongoDB", "Tailwind CSS", "JWT", "GitHub Actions", "Python"],
    yearsOfExperience: 3,
    availability: "2 weeks",
    employmentType: ["Full-time", "Contract"],
    compensationMin: 900,
    compensationMax: 1500,
    portfolioLinks: {
      github: "https://github.com/Okpara007",
      linkedin: "https://www.linkedin.com/in/delight-okpara-674339249/",
    },
    resumeUrl: "https://firebasestorage.googleapis.com/v0/b/mikeokpechi-e4331.firebasestorage.app/o/resumes%2F1754303338291_Delight_Okpara%20Resume.pdf?alt=media&token=92bb882f-9948-4efa-b444-c9c38f33df51",
    featured: true,
  },
  {
    id: "chukwuma-emmanuella",
    name: "Chukwuma Emmanuella",
    headline: "Software Engineer · Java, Node.js, Python & AI Systems",
    bio: "Software engineer with over 4 years of experience designing and developing scalable, high-performance applications. My expertise spans backend, frontend, and AI-driven systems, with a strong command of Java, Node.js, Python and databases such as PostgreSQL and MongoDB. I've delivered solutions across fintech, education, and automation industries.",
    location: "Lagos, Nigeria",
    country: "Nigeria",
    profilePhotoUrl: "https://res.cloudinary.com/dwwzrtzb8/image/upload/v1754676553/profile_images/IMG_3821.jpeg.jpg",
    sectors: ["software_engineering", "ai_ml"],
    primarySkills: ["Java", "Node.js", "Python", "TypeScript"],
    secondarySkills: ["Spring Boot", "Nest.js", "Express.js", "Flask", "React.js", "PostgreSQL", "MongoDB"],
    yearsOfExperience: 4,
    availability: "2 weeks",
    employmentType: ["Full-time", "Contract"],
    compensationMin: 1100,
    compensationMax: 1800,
    portfolioLinks: {
      github: "https://github.com/ch3lla",
      linkedin: "https://www.linkedin.com/in/emmanuella-chukwuma/",
    },
    resumeUrl: "https://firebasestorage.googleapis.com/v0/b/mikeokpechi-e4331.firebasestorage.app/o/resumes%2F1754676022878_CHUKWUMA_CV_2025.docx.pdf?alt=media&token=ecb6681d-4f42-4105-b32b-3be7a65b0d9c",
    featured: false,
  },
  {
    id: "medhat-mostafa-atya",
    name: "Medhat Mostafa Atya",
    headline: "Mobile App Developer · Flutter, Kotlin & iOS",
    bio: "Passionate mobile developer with over 5 years of experience building apps for both Android (Java/Kotlin) and Flutter (cross-platform). Expert in state management (Bloc, Provider, GetX, Riverpod), payment gateways, Google Maps, real-time apps, and deploying to both Play Store and App Store.",
    location: "Cairo, Egypt",
    country: "Egypt",
    profilePhotoUrl: "https://res.cloudinary.com/dwwzrtzb8/image/upload/v1755388301/profile_images/20231224_184535.png.png",
    sectors: ["mobile_development"],
    primarySkills: ["Flutter", "Kotlin", "Dart", "Firebase"],
    secondarySkills: ["Node.js", "React.js", "Python", "REST APIs", "WebSockets", "CI/CD"],
    yearsOfExperience: 6,
    availability: "2 weeks",
    employmentType: ["Full-time", "Contract"],
    compensationMin: 1400,
    compensationMax: 2200,
    portfolioLinks: {
      github: "https://github.com/Mmd7t",
      linkedin: "https://www.linkedin.com/in/medhat-mostafa-mmd7t",
    },
    resumeUrl: "https://firebasestorage.googleapis.com/v0/b/mikeokpechi-e4331.firebasestorage.app/o/resumes%2F1755388255252_Medhat%20CV%20v8.pdf?alt=media&token=840ea875-1e1b-48b7-972b-f579129fdddf",
    featured: false,
  },
  {
    id: "anjolaoluwa-ajayi",
    name: "Anjolaoluwa Ajayi",
    headline: "Data Scientist · LLMs, RAG & AI Engineering",
    bio: "CS Graduate with First Class Honours. Top Data and AI Voice on Medium. Completed a dozen data science and AI projects ranging from RAG chatbots and analytics dashboards for NGOs to full-stack AI applications for startups. Looking to help somebody build their next cool AI application.",
    location: "Lagos, Nigeria",
    country: "Nigeria",
    profilePhotoUrl: "https://res.cloudinary.com/dwwzrtzb8/image/upload/v1755176536/profile_images/IMG-20250729-WA0081.jpg.jpg",
    sectors: ["ai_ml", "data_analytics"],
    primarySkills: ["LLMs", "RAG", "Machine Learning", "Python"],
    secondarySkills: ["AI Agents", "GCP", "Data Analysis", "TensorFlow"],
    yearsOfExperience: 3,
    availability: "Immediate",
    employmentType: ["Full-time", "Contract"],
    compensationMin: 800,
    compensationMax: 1400,
    portfolioLinks: {
      github: "https://github.com/lifewjola",
      linkedin: "https://www.linkedin.com/in/lifewjola/",
    },
    resumeUrl: "https://firebasestorage.googleapis.com/v0/b/mikeokpechi-e4331.firebasestorage.app/o/resumes%2F1755176502714_Anjolaoluwa-Ajayi-FlowCV-Resume-20241122%20(1).pdf?alt=media&token=79b035d9-93f2-49d9-8b1c-5fa8bb2ccebd",
    featured: false,
  },
  {
    id: "omorinsola-makinde",
    name: "Omorinsola Makinde",
    headline: "AI/ML Engineer · Predictive Models & Computer Vision",
    bio: "Machine Learning Engineer who helps businesses turn complex data into smarter, faster decisions. My focus is building AI solutions that actually work — from predictive models to deep learning systems — and delivering them in clean pipelines. I care about real-world impact.",
    location: "Lagos, Nigeria",
    country: "Nigeria",
    profilePhotoUrl: "https://res.cloudinary.com/dwwzrtzb8/image/upload/v1755083058/profile_images/image%20%285%29.jpeg.jpg",
    sectors: ["ai_ml", "data_analytics"],
    primarySkills: ["Machine Learning", "Python", "TensorFlow", "PyTorch"],
    secondarySkills: ["SQL", "Computer Vision", "Predictive Modeling", "Data Science", "PostgreSQL"],
    yearsOfExperience: 2,
    availability: "2 weeks",
    employmentType: ["Full-time", "Contract"],
    compensationMin: 700,
    compensationMax: 1200,
    portfolioLinks: {
      github: "https://github.com/Omo-Rinsola",
      linkedin: "https://www.linkedin.com/in/omorinsola-makinde",
    },
    resumeUrl: "https://firebasestorage.googleapis.com/v0/b/mikeokpechi-e4331.firebasestorage.app/o/resumes%2F1755087546374_Makinde-Omorinsola-FlowCV-Resume-20250813.pdf?alt=media&token=0542a34f-6a57-4823-9131-1c8b2970bf6b",
    featured: false,
  },
  {
    id: "raynan-wuyep",
    name: "Raynan Wuyep",
    headline: "Full Stack Developer · React, Node.js & AI/ML",
    bio: "Passionate fullstack developer with a strong foundation in modern web technologies. My expertise spans React, Next.js, TypeScript, and Tailwind CSS, allowing me to create responsive, performant, and user-friendly web applications. Beyond fullstack, I have a deep interest in AI and machine learning.",
    location: "Jos, Nigeria",
    country: "Nigeria",
    profilePhotoUrl: "https://res.cloudinary.com/dwwzrtzb8/image/upload/v1755170245/profile_images/IMG_1673.jpeg.jpg",
    sectors: ["software_engineering", "web_development", "ai_ml"],
    primarySkills: ["React", "TypeScript", "Next.js", "Node.js"],
    secondarySkills: ["FastAPI", "Flask", "Django", "MongoDB", "Redux", "TailwindCSS"],
    yearsOfExperience: 4,
    availability: "2 weeks",
    employmentType: ["Full-time"],
    compensationMin: 1000,
    compensationMax: 1600,
    portfolioLinks: {
      github: "https://github.com/Raynan00/",
      linkedin: "https://www.linkedin.com/in/raynan-wuyep",
    },
    resumeUrl: "https://firebasestorage.googleapis.com/v0/b/mikeokpechi-e4331.firebasestorage.app/o/resumes%2F1755170209439_Raynan%20Wuyep%20Developer%20Resume.pdf?alt=media&token=f0691e92-be55-43c3-9a22-2ce2db0b907e",
    featured: false,
  },
  {
    id: "lois-okereke",
    name: "Lois Okereke",
    headline: "Frontend Developer · React, Next.js & SaaS Interfaces",
    bio: "Creative front-end developer who loves turning ideas into clean, interactive web experiences. I thrive on blending sleek, modern design with seamless functionality. My toolkit includes React, Next.js, and Tailwind CSS, and I enjoy collaborating with founders and product teams to bring SaaS products to life.",
    location: "Lagos, Nigeria",
    country: "Nigeria",
    profilePhotoUrl: "https://res.cloudinary.com/dwwzrtzb8/image/upload/v1755177584/profile_images/me.jpg.jpg",
    coverMediaUrl: "https://res.cloudinary.com/dwwzrtzb8/image/upload/v1755177625/profile_images/Lois1.jpg.jpg",
    sectors: ["web_development"],
    primarySkills: ["React", "Next.js", "TypeScript", "Tailwind CSS"],
    secondarySkills: ["JavaScript", "Redux", "React Query", "Framer Motion", "REST APIs", "Figma"],
    yearsOfExperience: 5,
    availability: "2 weeks",
    employmentType: ["Full-time", "Contract"],
    compensationMin: 1000,
    compensationMax: 1600,
    portfolioLinks: {
      portfolio: "https://loisnextjsportfolio.netlify.app/",
      linkedin: "https://www.linkedin.com/in/lois-okereke",
    },
    resumeUrl: "https://firebasestorage.googleapis.com/v0/b/mikeokpechi-e4331.firebasestorage.app/o/resumes%2F1755176352831_Lois-Okereke-Resume.pdf?alt=media&token=52a621d8-d61a-46af-a6e4-119483ff6606",
    featured: false,
  },
  {
    id: "udofia-unwana-abasi",
    name: "Udofia Unwana-Abasi",
    headline: "Backend Developer · Django, React & AI APIs",
    bio: "Versatile and innovative developer with experience in Django, React, and API development, specializing in building practical solutions to real-world problems. My work reflects a balance of technical precision and user-focused design, leveraging DRF Spectacular, WebSockets, SimpleJWT, and fine-tuned LLMs.",
    location: "Lagos, Nigeria",
    country: "Nigeria",
    profilePhotoUrl: "https://res.cloudinary.com/dwwzrtzb8/image/upload/v1754935992/profile_images/8F87F741-D265-4989-BD2A-5476654AEAE8.jpeg.jpg",
    coverMediaUrl: "https://res.cloudinary.com/dwwzrtzb8/image/upload/v1754935452/profile_images/IMG_1186.jpeg.jpg",
    sectors: ["software_engineering", "ai_ml"],
    primarySkills: ["Django", "React", "Python", "AWS"],
    secondarySkills: ["ExpressJS", "LangChain", "REST APIs", "PostgreSQL"],
    yearsOfExperience: 3,
    availability: "2 weeks",
    employmentType: ["Full-time", "Contract"],
    compensationMin: 800,
    compensationMax: 1400,
    portfolioLinks: {
      github: "https://github.com/Uwanaaa",
      linkedin: "https://www.linkedin.com/in/uwana-udofia/",
    },
    resumeUrl: "https://firebasestorage.googleapis.com/v0/b/mikeokpechi-e4331.firebasestorage.app/o/resumes%2F1755082662412_Udofia_Unwana-Abasi_1685455363.pdf?alt=media&token=28984c79-1bdc-4e27-b7c2-16d654e1b115",
    featured: false,
  },
  {
    id: "bishop-edet-uko",
    name: "Bishop Edet-Uko",
    headline: "DevOps Engineer · AWS, Kubernetes & Docker",
    bio: "DevOps engineer with 2+ years experience building and deploying quality and secure cloud-based infrastructure. Passionate about learning new tools and new cultures, improving teams and personal development.",
    location: "Lagos, Nigeria",
    country: "Nigeria",
    profilePhotoUrl: "https://res.cloudinary.com/dwwzrtzb8/image/upload/v1754293305/profile_images/WhatsApp%20Image%202025-08-04%20at%2008.41.23_be661f01.jpg.jpg",
    coverMediaUrl: "https://res.cloudinary.com/dwwzrtzb8/image/upload/v1754293308/profile_images/WhatsApp%20Image%202025-08-04%20at%2008.38.15_8805652a.jpg.jpg",
    sectors: ["devops_infrastructure"],
    primarySkills: ["AWS", "Kubernetes", "Docker", "Terraform"],
    secondarySkills: ["GitHub Actions", "Jenkins", "Linux", "CI/CD"],
    yearsOfExperience: 3,
    availability: "2 weeks",
    employmentType: ["Full-time", "Contract"],
    compensationMin: 800,
    compensationMax: 1400,
    portfolioLinks: {
      linkedin: "https://www.linkedin.com/in/bishop-edet-uko",
    },
    resumeUrl: "https://firebasestorage.googleapis.com/v0/b/mikeokpechi-e4331.firebasestorage.app/o/resumes%2F1754294863841_Bishop-Edet-Uko-DevOps-CV.pdf?alt=media&token=78d969ff-44cf-41a1-aa98-be5cf0c93039",
    featured: false,
  },
  {
    id: "opatola-bolaji",
    name: "Opatola Bolaji",
    headline: "Full Stack & AI Developer · React Native, Node.js & LangChain",
    bio: "Full-Stack Developer specializing in crafting end-to-end digital solutions that combine robust functionality with exceptional user experience. I integrate Python-based AI technologies including LangChain, LangGraph, and Hugging Face to create smart, context-aware applications. I thrive at the intersection of technology, AI, and innovation.",
    location: "Lagos, Nigeria",
    country: "Nigeria",
    profilePhotoUrl: "https://res.cloudinary.com/dwwzrtzb8/image/upload/v1754664606/profile_images/bolaji.jpg.jpg",
    sectors: ["software_engineering", "ai_ml", "mobile_development"],
    primarySkills: ["React.js", "Node.js", "React Native", "Python"],
    secondarySkills: ["Next.js", "FastAPI", "MongoDB", "LangChain", "TypeScript", "Firebase"],
    yearsOfExperience: 3,
    availability: "2 weeks",
    employmentType: ["Full-time", "Contract"],
    compensationMin: 800,
    compensationMax: 1400,
    portfolioLinks: {
      github: "https://github.com/emperorbj",
      linkedin: "https://www.linkedin.com/in/bolaji-opatola",
    },
    resumeUrl: "https://firebasestorage.googleapis.com/v0/b/mikeokpechi-e4331.firebasestorage.app/o/resumes%2F1754667439128_MyResume.pdf?alt=media&token=2623bdb0-047b-4c9e-8046-666cefe8d8e6",
    featured: false,
  },
  {
    id: "adegbite-damola",
    name: "Adegbite Damola",
    headline: "Backend Developer · Node.js, TypeScript & AWS",
    bio: "I develop production-ready backend systems using Node.js, TypeScript, and AWS cloud services. My experience spans API development with Express, performance optimization with Redis, containerization with Docker, and cloud deployment on EC2/S3. I'm passionate about clean architecture and seeking opportunities to build systems that scale.",
    location: "Lagos, Nigeria",
    country: "Nigeria",
    profilePhotoUrl: "https://res.cloudinary.com/dwwzrtzb8/image/upload/v1754941932/profile_images/IMG_20250406_064459.jpg.jpg",
    sectors: ["software_engineering", "devops_infrastructure"],
    primarySkills: ["Node.js", "TypeScript", "AWS", "Docker"],
    secondarySkills: ["Express.js", "Redis", "MongoDB", "MySQL", "Nginx", "REST APIs"],
    yearsOfExperience: 3,
    availability: "2 weeks",
    employmentType: ["Full-time", "Contract", "Part-time"],
    compensationMin: 800,
    compensationMax: 1400,
    portfolioLinks: {
      linkedin: "https://www.linkedin.com/in/damola-adegbite",
    },
    resumeUrl: "https://firebasestorage.googleapis.com/v0/b/mikeokpechi-e4331.firebasestorage.app/o/resumes%2F1754941863951_Adegbite%20Damola%20cv%20(1).pdf?alt=media&token=cbb124e3-62cc-4e62-a885-0c2629bf3676",
    featured: false,
  },
  {
    id: "emmanuel-excellent",
    name: "Emmanuel Excellent",
    headline: "Full Stack Developer · React, Next.js & Supabase",
    bio: "I design and develop high-performing, user-friendly web applications with React, Next.js, and Supabase, delivering seamless experiences from concept to deployment. I've built multi-vendor e-commerce platforms, AI-powered note-taking apps, real-time collaboration tools, and marketplace/SaaS platforms.",
    location: "Lagos, Nigeria",
    country: "Nigeria",
    profilePhotoUrl: "https://res.cloudinary.com/dwwzrtzb8/image/upload/v1755254710/profile_images/IMG_1355.jpeg.jpg",
    sectors: ["software_engineering", "web_development"],
    primarySkills: ["React", "Next.js", "TypeScript", "Supabase"],
    secondarySkills: ["TailwindCSS", "NodeJS", "FastAPI", "SQL"],
    yearsOfExperience: 5,
    availability: "2 weeks",
    employmentType: ["Full-time", "Contract"],
    compensationMin: 1000,
    compensationMax: 1700,
    portfolioLinks: {
      github: "https://github.com/emmaexcellent",
      linkedin: "https://www.linkedin.com/in/emmanuel-excellent",
    },
    resumeUrl: "https://firebasestorage.googleapis.com/v0/b/mikeokpechi-e4331.firebasestorage.app/o/resumes%2F1755254592605_fullstack_resume.pdf?alt=media&token=525b3347-1987-444e-93b6-0b8031432658",
    featured: false,
  },
  {
    id: "ayowole-sodipe",
    name: "Ayowole Sodipe",
    headline: "Full Stack Mobile Developer · Flutter & Node.js",
    bio: "Flutter Developer and Node.js engineer who has built 2 production apps used by 1000+ businesses across Nigeria. Currently an intern Flutter Developer at Pinpoint. I'm fluent in Flutter and Node.js and passionate about building impactful cross-platform products.",
    location: "Abeokuta, Nigeria",
    country: "Nigeria",
    profilePhotoUrl: "https://res.cloudinary.com/dwwzrtzb8/image/upload/v1754752927/profile_images/JSV09815.png.png",
    coverMediaUrl: "https://res.cloudinary.com/dwwzrtzb8/image/upload/v1754753137/profile_images/JSV09815copy.png.png",
    sectors: ["mobile_development", "software_engineering"],
    primarySkills: ["Flutter", "Dart", "Node.js", "JavaScript"],
    secondarySkills: ["Express", "Python", "Firebase", "REST APIs"],
    yearsOfExperience: 2,
    availability: "2 weeks",
    employmentType: ["Full-time", "Contract"],
    compensationMin: 600,
    compensationMax: 1100,
    portfolioLinks: {
      portfolio: "https://ayowolesodipe.vercel.app",
      linkedin: "https://www.linkedin.com/in/ayowolesodipe/",
    },
    resumeUrl: "https://firebasestorage.googleapis.com/v0/b/mikeokpechi-e4331.firebasestorage.app/o/resumes%2F1754753454397_Ayowole-Sodipe-FlowCV-Resume-20250809.pdf?alt=media&token=bb1f344a-df69-46bb-95d8-0dfffcbbe5a5",
    featured: false,
  },
  {
    id: "ireoluwatomiwa-adekoya",
    name: "Ireoluwatomiwa Adekoya",
    headline: "Fullstack Developer · Angular, React & Node.js",
    bio: "Builder at heart with a track record of turning ideas into products that solve real problems. Founder of FirstRep, a social accountability fitness app. I balance professional software development with self-driven projects and thrive in fast-moving environments. I merge technical execution, creative storytelling, and disciplined work ethic.",
    location: "Lagos, Nigeria",
    country: "Nigeria",
    profilePhotoUrl: "https://res.cloudinary.com/dwwzrtzb8/image/upload/v1754743979/profile_images/IMG_0390%20%281%29.jpg.jpg",
    sectors: ["software_engineering", "web_development"],
    primarySkills: ["JavaScript", "TypeScript", "React.js", "Angular"],
    secondarySkills: ["Node.js", "Next.js", "MongoDB", "Docker", "Jest", "Playwright", "OpenAI APIs"],
    yearsOfExperience: 2,
    availability: "2 weeks",
    employmentType: ["Full-time", "Contract"],
    compensationMin: 700,
    compensationMax: 1200,
    portfolioLinks: {
      github: "https://github.com/koyaboy",
      linkedin: "https://www.linkedin.com/in/ireoluwatomiwa-adekoya/",
    },
    resumeUrl: "https://firebasestorage.googleapis.com/v0/b/mikeokpechi-e4331.firebasestorage.app/o/resumes%2F1754744562860_Resume%20New.pdf?alt=media&token=6885867f-c271-4143-920b-87d7027465c9",
    featured: false,
  },
  {
    id: "obinna-achazie",
    name: "Obinna Anthony Achazie",
    headline: "Frontend Developer · React, Next.js & Full Stack",
    bio: "Web Developer and Software Engineer who loves building things that actually make people's lives easier. I've worked across front-end and back-end, comfortable polishing UI details as much as solving tough technical problems under the hood. I thrive in collaborative teams and enjoy turning complex ideas into clean, working solutions.",
    location: "Lagos, Nigeria",
    country: "Nigeria",
    profilePhotoUrl: "https://res.cloudinary.com/dwwzrtzb8/image/upload/v1755513531/profile_images/Passport.jpg.jpg",
    coverMediaUrl: "https://res.cloudinary.com/dwwzrtzb8/image/upload/v1755513652/profile_images/dasharath-sunar-KHZSC0eg9HU-unsplash.jpeg.jpg",
    sectors: ["web_development", "software_engineering"],
    primarySkills: ["React JS", "Next.js", "Python", "MongoDB"],
    secondarySkills: ["CSS", "SQL", "REST APIs"],
    yearsOfExperience: 3,
    availability: "Immediate",
    employmentType: ["Full-time", "Contract"],
    compensationMin: 700,
    compensationMax: 1200,
    portfolioLinks: {
      github: "https://github.com/acha-jr",
      linkedin: "https://linkedin.com/in/obinna-achazie",
    },
    resumeUrl: "https://firebasestorage.googleapis.com/v0/b/mikeokpechi-e4331.firebasestorage.app/o/resumes%2F1755513365303_Obinna_Achazie_Resume.pdf?alt=media&token=c44489b6-864b-4a2c-801d-7c4dd0381ffe",
    featured: false,
  },
  {
    id: "treasure-aiyedun",
    name: "Treasure Aiyedun",
    headline: "Frontend Developer · React, TypeScript & Next.js",
    bio: "Frontend Developer with over 2 years of hands-on experience building responsive, user-friendly web applications using React, TypeScript, and Tailwind CSS. I've worked on solo and collaborative projects — delivering clean, scalable UIs, integrating APIs like Stripe, Supabase, and Recharts.",
    location: "Lagos, Nigeria",
    country: "Nigeria",
    profilePhotoUrl: "https://res.cloudinary.com/dwwzrtzb8/image/upload/v1754328276/profile_images/1000767375.png.png",
    coverMediaUrl: "https://res.cloudinary.com/dwwzrtzb8/image/upload/v1754328221/profile_images/1000767365.jpg.jpg",
    sectors: ["web_development"],
    primarySkills: ["React", "TypeScript", "Tailwind CSS", "Next.js"],
    secondarySkills: ["JavaScript", "HTML5", "CSS3", "REST API Integration", "Material-UI"],
    yearsOfExperience: 2,
    availability: "2 weeks",
    employmentType: ["Full-time", "Contract"],
    compensationMin: 600,
    compensationMax: 1000,
    portfolioLinks: {
      portfolio: "https://treasureaiyedun.vercel.app/",
      linkedin: "https://www.linkedin.com/in/treasureaiyedun",
    },
    resumeUrl: "https://firebasestorage.googleapis.com/v0/b/mikeokpechi-e4331.firebasestorage.app/o/resumes%2F1754330606184_Treasure%20Aiyedun%20-%20Frontend%20Engineer%20Resume.pdf?alt=media&token=e234727b-14f0-4ffa-a1c4-45284c1d5376",
    featured: false,
  },
  {
    id: "kelvin-omoluyi",
    name: "Kelvin Matthias Omoluyi",
    headline: "Frontend Web Developer · React, Next.js & SEO",
    bio: "Creative and results-driven Web Developer who blends beautiful design with seamless functionality. I specialize in building high-converting, responsive web applications that are not just visually striking, but also optimized for speed, performance, and top-tier SEO visibility.",
    location: "Lagos, Nigeria",
    country: "Nigeria",
    profilePhotoUrl: "https://res.cloudinary.com/dwwzrtzb8/image/upload/v1754906240/profile_images/pfp2.png.png",
    coverMediaUrl: "https://res.cloudinary.com/dwwzrtzb8/image/upload/v1754906208/profile_images/home%20section.PNG.png",
    sectors: ["web_development", "software_engineering"],
    primarySkills: ["React", "Next.js", "JavaScript", "Figma"],
    secondarySkills: ["HTML/CSS", "PHP", "MongoDB", "SQL", "Framer-Motion", "AppWrite"],
    yearsOfExperience: 2,
    availability: "2 weeks",
    employmentType: ["Full-time", "Contract"],
    compensationMin: 600,
    compensationMax: 1000,
    portfolioLinks: {
      github: "https://github.com/KelvinOmoluyi",
      linkedin: "https://www.linkedin.com/in/kelvin-omoluyi-6aa90031b/",
    },
    resumeUrl: "https://firebasestorage.googleapis.com/v0/b/mikeokpechi-e4331.firebasestorage.app/o/resumes%2F1754906407390_Kelvin%20Omoluyi_.pdf?alt=media&token=7d36311d-ed8d-468b-a66d-478086b39ce4",
    featured: false,
  },
  {
    id: "izuehie-luckyprince",
    name: "Izuehie Luckyprince Sochimaobi",
    headline: "Frontend Developer · React, TypeScript & Web3",
    bio: "Web developer passionate about building AI-driven, user-focused web experiences. I work mostly with React and enjoy creating intuitive, real-time interfaces. I dabble in Web3 from time to time and explore tools that push the boundaries of modern web development.",
    location: "Lagos, Nigeria",
    country: "Nigeria",
    profilePhotoUrl: "https://res.cloudinary.com/dwwzrtzb8/image/upload/v1754318634/profile_images/WhatsApp%20Image%202025-05-30%20at%2021.43.54_1f53fa45.jpg.jpg",
    coverMediaUrl: "https://res.cloudinary.com/dwwzrtzb8/image/upload/v1754319797/profile_images/1500x500.jpeg.jpg",
    sectors: ["web_development", "vibe_coding"],
    primarySkills: ["React", "TypeScript", "Tailwind", "JavaScript"],
    secondarySkills: ["Web3", "Real-time UIs", "REST APIs"],
    yearsOfExperience: 2,
    availability: "2 weeks",
    employmentType: ["Full-time", "Contract"],
    compensationMin: 600,
    compensationMax: 1000,
    portfolioLinks: {
      portfolio: "https://onrooleyy.vercel.app",
      linkedin: "https://www.linkedin.com/in/luckyprince-sochima-622948346",
    },
    resumeUrl: "https://firebasestorage.googleapis.com/v0/b/mikeokpechi-e4331.firebasestorage.app/o/resumes%2F1754334880676_Izuehie%20Luckyprince%20CV.pdf?alt=media&token=9f9e5850-aac7-48cc-a99b-b28b58ccdabf",
    featured: false,
  },
  {
    id: "farirai-masocha",
    name: "Farirai Masocha",
    headline: "Full Stack Developer · React, Laravel & Next.js",
    bio: "Passionate about creating solutions that tackle my own pain points. Projects like Payfari and Linkgenie have been instrumental in helping me build small, targeted micro SaaS apps that solve real problems.",
    location: "Harare, Zimbabwe",
    country: "Zimbabwe",
    profilePhotoUrl: "https://res.cloudinary.com/dwwzrtzb8/image/upload/v1754846073/profile_images/1000002847.jpg.jpg",
    sectors: ["software_engineering", "web_development"],
    primarySkills: ["React", "Next.js", "Laravel", "JavaScript"],
    secondarySkills: ["TypeScript", "PHP", "REST APIs", "MySQL"],
    yearsOfExperience: 3,
    availability: "Immediate",
    employmentType: ["Full-time", "Contract"],
    compensationMin: 700,
    compensationMax: 1200,
    portfolioLinks: {
      github: "https://github.com/fariraimasocha",
      linkedin: "https://www.linkedin.com/in/fariraimasocha",
    },
    resumeUrl: "https://firebasestorage.googleapis.com/v0/b/mikeokpechi-e4331.firebasestorage.app/o/resumes%2F1754846251342_Farirai%20James%20Resume.pdf?alt=media&token=6a3fe367-6136-499b-8cc4-8ec97235d64a",
    featured: false,
  },
  {
    id: "elizabeth-akinbola",
    name: "Elizabeth Akinbola",
    headline: "Web Developer · JavaScript, React & No-Code",
    bio: "Web Developer fusing creative vision with technical precision to transform complex ideas into intuitive, high-impact digital experiences. Certified by Meta and Codeflare, grounded in a BSc in Mass Communication. My communication background allows me to translate technical complexity into clear, human language.",
    location: "Lagos, Nigeria",
    country: "Nigeria",
    profilePhotoUrl: "https://res.cloudinary.com/dwwzrtzb8/image/upload/v1754991561/profile_images/IMG_20250811_100155.jpg.jpg",
    coverMediaUrl: "https://res.cloudinary.com/dwwzrtzb8/image/upload/v1754972489/profile_images/IMG_20250811_101840.jpg.jpg",
    sectors: ["web_development", "marketing"],
    primarySkills: ["JavaScript", "React", "PHP", "WordPress"],
    secondarySkills: ["Firebase", "MySQL", "HTML", "CSS", "Content Strategy"],
    yearsOfExperience: 3,
    availability: "2 weeks",
    employmentType: ["Full-time", "Contract"],
    compensationMin: 600,
    compensationMax: 1100,
    portfolioLinks: {
      github: "https://github.com/lizeeraphael",
      linkedin: "https://www.linkedin.com/in/akinbola-elizabeth-ba770217b",
    },
    resumeUrl: "https://firebasestorage.googleapis.com/v0/b/mikeokpechi-e4331.firebasestorage.app/o/resumes%2F1754999584809_Akinbola%20Elizabeth%20(Web%20Dev)%20Resume%20New%20(1).pdf?alt=media&token=483c36c3-98d6-423a-a739-a644bd08f29e",
    featured: false,
  },
  {
    id: "goodness-uwojeyah",
    name: "Goodness Uwojeyah",
    headline: "Product Designer & Content Creator · Figma & Web Dev",
    bio: "Versatile web developer, UI/UX designer, and content creator driven by a passion for crafting impactful digital experiences. With a strong blend of technical skill, design expertise, and storytelling, I help brands and communities connect with their audience in meaningful ways.",
    location: "Lagos, Nigeria",
    country: "Nigeria",
    profilePhotoUrl: "https://res.cloudinary.com/dwwzrtzb8/image/upload/v1754668835/profile_images/1736290503131%20%281%29.jpeg.jpg",
    coverMediaUrl: "https://res.cloudinary.com/dwwzrtzb8/image/upload/v1754668762/profile_images/DSC_7532.JPG.jpg",
    sectors: ["design_ux", "marketing"],
    primarySkills: ["Figma", "UI/UX Design", "Framer", "WordPress"],
    secondarySkills: ["HTML", "CSS", "JavaScript", "Prototyping", "Content Creation", "Social Media Strategy"],
    yearsOfExperience: 3,
    availability: "2 weeks",
    employmentType: ["Full-time", "Contract"],
    compensationMin: 700,
    compensationMax: 1200,
    portfolioLinks: {
      dribbble: "https://www.behance.net/goodnessuwojeyah",
      linkedin: "https://www.linkedin.com/in/goodness-uwojeyah-80b25a259",
    },
    resumeUrl: "https://firebasestorage.googleapis.com/v0/b/mikeokpechi-e4331.firebasestorage.app/o/resumes%2F1754668489837_Goodness%20Uwojeyah%20CV.pdf?alt=media&token=c876bed3-904a-45b0-baa4-810a9793eb8d",
    featured: false,
  },
  {
    id: "goodness-swift",
    name: "Goodness Swift",
    headline: "Product Designer · UI/UX for Healthtech, Fintech & SaaS",
    bio: "Product Designer turning 'make it look nice' into functional experiences across healthtech, fintech, SaaS & e-commerce. I use a combination of Figma, no-code tools, and user research to create interfaces people actually enjoy using.",
    location: "Lagos, Nigeria",
    country: "Nigeria",
    profilePhotoUrl: "https://res.cloudinary.com/dwwzrtzb8/image/upload/v1755090186/profile_images/IMG_2703.jpeg.jpg",
    sectors: ["design_ux"],
    primarySkills: ["UI/UX Design", "Web Design", "Mobile App Design", "Figma"],
    secondarySkills: ["Framer", "No-Code", "Prototyping"],
    yearsOfExperience: 3,
    availability: "2 weeks",
    employmentType: ["Full-time", "Contract"],
    compensationMin: 700,
    compensationMax: 1200,
    portfolioLinks: {
      portfolio: "https://goodnessswiftportfolio.framer.website/",
      linkedin: "https://www.linkedin.com/in/goodness-swift-031904202",
    },
    resumeUrl: "https://firebasestorage.googleapis.com/v0/b/mikeokpechi-e4331.firebasestorage.app/o/resumes%2F1755090394686_EMENIKE%2C%20Goodness%20Mmesomachukwu.pdf?alt=media&token=d7ff032c-3e5d-47cd-a4c1-b53990652741",
    featured: false,
  },
  {
    id: "edet-edmund",
    name: "Edet Edmund Ememobong",
    headline: "UI/UX Designer · Figma, Adobe & Frontend Dev",
    bio: "UI/UX Designer, Graphics designer, and Brand designer with over 2 years of experience. Graduate of software engineering with a 2.1. A creative individual who sees the creative side of everything — I design websites, mobile apps, clothes, posters, and more. Open to collaborating and improving my skills.",
    location: "Lagos, Nigeria",
    country: "Nigeria",
    profilePhotoUrl: "https://res.cloudinary.com/dwwzrtzb8/image/upload/v1754677279/profile_images/IMG_6254.jpeg.jpg",
    coverMediaUrl: "https://res.cloudinary.com/dwwzrtzb8/image/upload/v1754677244/profile_images/e54561ab-765e-473b-bd5d-a709dace5800.jpeg.jpg",
    sectors: ["design_ux"],
    primarySkills: ["Figma", "Adobe Illustrator", "Adobe Photoshop", "UI/UX Design"],
    secondarySkills: ["Canva", "CapCut", "React.js", "Video Editing"],
    yearsOfExperience: 3,
    availability: "2 weeks",
    employmentType: ["Full-time", "Contract"],
    compensationMin: 600,
    compensationMax: 1100,
    portfolioLinks: {
      dribbble: "https://www.behance.net/EdetEdmund",
      linkedin: "https://www.linkedin.com/in/edmund-edet",
    },
    resumeUrl: "https://firebasestorage.googleapis.com/v0/b/mikeokpechi-e4331.firebasestorage.app/o/resumes%2F1754677546866_Resume%20new(edmund).pdf?alt=media&token=5b143d09-3dfd-4709-ba50-1e143ed5e240",
    featured: false,
  },
  {
    id: "eze-chukwuebuka-brendan",
    name: "Eze Chukwuebuka Brendan",
    headline: "Product Designer · Figma & Adobe Creative Suite",
    bio: "Product designer with 2 years of experience creating user-focused digital experiences. I combine design thinking with attention to detail to deliver interfaces that are both beautiful and functional.",
    location: "Lagos, Nigeria",
    country: "Nigeria",
    profilePhotoUrl: "https://res.cloudinary.com/dwwzrtzb8/image/upload/v1754295906/profile_images/IMG_7776.png.png",
    sectors: ["design_ux"],
    primarySkills: ["Figma", "Adobe Creative Suite", "UI Design", "Prototyping"],
    secondarySkills: ["UX Research", "Wireframing"],
    yearsOfExperience: 2,
    availability: "Immediate",
    employmentType: ["Full-time", "Contract"],
    compensationMin: 500,
    compensationMax: 900,
    portfolioLinks: {
      dribbble: "https://www.behance.net/brendan_c_eze",
      linkedin: "https://www.linkedin.com/in/chukwuebuka-eze-a1a194169",
    },
    resumeUrl: "https://firebasestorage.googleapis.com/v0/b/mikeokpechi-e4331.firebasestorage.app/o/resumes%2F1754302260211_Chukwuebuka%20CV.pdf?alt=media&token=a35502ed-b32c-41da-86ae-14341457d037",
    featured: false,
  },
  {
    id: "bekwa-undie",
    name: "Bekwa Undie",
    headline: "Product Designer & Framer Developer · No-Code Expert",
    bio: "Product designer and Framer Developer focused on creating digital experiences that help businesses grow. I have a track record of turning ideas from mere concepts into highly converting digital products — mobile apps, web dashboards, responsive websites, and landing pages. I'm all about user satisfaction and business success.",
    location: "Lagos, Nigeria",
    country: "Nigeria",
    profilePhotoUrl: "https://res.cloudinary.com/dwwzrtzb8/image/upload/v1754673762/profile_images/My%20Image.png.png",
    coverMediaUrl: "https://res.cloudinary.com/dwwzrtzb8/image/upload/v1754673785/profile_images/IMG_3157.jpeg.jpg",
    sectors: ["design_ux", "web_development"],
    primarySkills: ["Figma", "Framer", "Product Design", "UI/UX"],
    secondarySkills: ["Wireframing", "Prototyping", "Design Systems", "User Research"],
    yearsOfExperience: 3,
    availability: "2 weeks",
    employmentType: ["Full-time", "Contract"],
    compensationMin: 700,
    compensationMax: 1200,
    portfolioLinks: {
      portfolio: "https://bekwaundie.framer.website/",
      linkedin: "https://www.linkedin.com/in/bekwaundie/",
    },
    resumeUrl: "https://firebasestorage.googleapis.com/v0/b/mikeokpechi-e4331.firebasestorage.app/o/resumes%2F1754673940066_Bekwa%20Undie%20Resume.docx.pdf?alt=media&token=b98d4807-f3dc-49d1-9fc3-a285e2aec65d",
    featured: false,
  },
  {
    id: "odetayo-isiaq",
    name: "Odetayo Isiaq Oladipupo",
    headline: "UI/UX Designer · No-Code & FlutterFlow Expert",
    bio: "No-Code UI/UX Designer helping startups and small businesses launch MVPs and scale quickly. I specialize in designing visually stunning and fully functional web and mobile applications using Figma, then developing in Webflow or FlutterFlow — cutting development time and costs significantly.",
    location: "Lagos, Nigeria",
    country: "Nigeria",
    profilePhotoUrl: "https://res.cloudinary.com/dwwzrtzb8/image/upload/v1754934555/profile_images/1751762926235.jpeg.jpg",
    sectors: ["design_ux", "web_development"],
    primarySkills: ["Figma", "Webflow", "FlutterFlow", "UI/UX Design"],
    secondarySkills: ["Wireframing", "Prototyping", "No-Code", "Framer"],
    yearsOfExperience: 3,
    availability: "2 weeks",
    employmentType: ["Full-time", "Contract"],
    compensationMin: 600,
    compensationMax: 1100,
    portfolioLinks: {
      portfolio: "https://contra.com/ola_of_figma_ynfsiw9a",
      linkedin: "https://www.linkedin.com/in/odetayo-ishaq-oladipupo-b731081b4/",
    },
    resumeUrl: "https://firebasestorage.googleapis.com/v0/b/mikeokpechi-e4331.firebasestorage.app/o/resumes%2F1754935321494_Odetayo%20Ishaq%20CV%20_.pdf?alt=media&token=6aeddc9c-cb75-4911-8c8a-9c6c6d60e83f",
    featured: false,
  },
  {
    id: "blessing-ugwu",
    name: "Blessing Ugwu",
    headline: "Product Designer · Figma, UI/UX & Prototyping",
    bio: "Creative and detail-oriented Product Designer passionate about crafting intuitive and visually engaging digital experiences. I have hands-on experience in UI/UX design, prototyping, and product strategy. I enjoy solving real-world problems through thoughtful design.",
    location: "Lagos, Nigeria",
    country: "Nigeria",
    profilePhotoUrl: "https://res.cloudinary.com/dwwzrtzb8/image/upload/v1755308038/profile_images/fine%20baby.jpg.jpg",
    coverMediaUrl: "https://res.cloudinary.com/dwwzrtzb8/image/upload/v1755308058/profile_images/cute%20baby.jpg.jpg",
    sectors: ["design_ux"],
    primarySkills: ["Figma", "UI/UX Design", "Prototyping", "Wireframing"],
    secondarySkills: ["User Research", "Interaction Design", "Visual Design"],
    yearsOfExperience: 1,
    availability: "Immediate",
    employmentType: ["Full-time", "Part-time", "Contract"],
    compensationMin: 400,
    compensationMax: 700,
    portfolioLinks: {
      dribbble: "https://www.behance.net/nwaoma",
      linkedin: "https://www.linkedin.com/in/blessing-ugwu-700b62371",
    },
    resumeUrl: "https://firebasestorage.googleapis.com/v0/b/mikeokpechi-e4331.firebasestorage.app/o/resumes%2F1755308553508_Blessing%20Ugwu%20Resume.pdf?alt=media&token=39f6d596-1d0b-4040-97da-65bb93bbbf1d",
    featured: false,
  },
  {
    id: "rejoice-obosi",
    name: "Obosi Rejoice Chibundom",
    headline: "Product Designer · UI/UX & Visual Design",
    bio: "Product Designer specialized in designing visually appealing, fully functional and scalable products. Passionate about solving problems and rendering user-centered solutions.",
    location: "Lagos, Nigeria",
    country: "Nigeria",
    profilePhotoUrl: "https://res.cloudinary.com/dwwzrtzb8/image/upload/v1754906068/profile_images/20250106_034805.jpg.jpg",
    coverMediaUrl: "https://res.cloudinary.com/dwwzrtzb8/image/upload/v1754906108/profile_images/Screenshot_20250811-104942_LinkedIn.jpg.jpg",
    sectors: ["design_ux", "marketing"],
    primarySkills: ["UI/UX Design", "Figma", "Prototyping", "Product Design"],
    secondarySkills: ["Video Editing", "Visual Design"],
    yearsOfExperience: 3,
    availability: "2 weeks",
    employmentType: ["Full-time", "Contract"],
    compensationMin: 600,
    compensationMax: 1100,
    portfolioLinks: {
      portfolio: "https://rejoiceobosi.framer.website",
      linkedin: "https://www.linkedin.com/in/rejoice-o-8752b0180",
    },
    resumeUrl: "https://firebasestorage.googleapis.com/v0/b/mikeokpechi-e4331.firebasestorage.app/o/resumes%2F1754907295275_1733126016446_CV%20-%20Rejoice%20Obosi.pdf?alt=media&token=f0639dc5-478b-4f69-a77c-3715d31226b7",
    featured: false,
  },
  {
    id: "makinde-bayonle",
    name: "Makinde Bayonle Adebola",
    headline: "Graphic & Brand Designer · Visual Identity Specialist",
    bio: "Creative Graphic Designer, Brand & Visual Identity Specialist, and Data Analyst. I blend design and strategy to help businesses stand out visually while making data-driven decisions that drive growth. From clean brand visuals to insightful analysis, I bring clarity, creativity, and consistency to every project.",
    location: "Lagos, Nigeria",
    country: "Nigeria",
    profilePhotoUrl: "https://res.cloudinary.com/dwwzrtzb8/image/upload/v1754239760/profile_images/1726007099633_aexfx2_2_0_0_edit.jpg.jpg",
    sectors: ["design_ux"],
    primarySkills: ["Graphic Design", "Brand Identity", "Visual Design", "Logo Design"],
    secondarySkills: ["Data Analysis", "Social Media Design"],
    yearsOfExperience: 3,
    availability: "2 weeks",
    employmentType: ["Full-time", "Contract"],
    compensationMin: 600,
    compensationMax: 1000,
    portfolioLinks: {
      linkedin: "https://www.linkedin.com/in/bayonle-makinde-635161290",
    },
    resumeUrl: "https://firebasestorage.googleapis.com/v0/b/mikeokpechi-e4331.firebasestorage.app/o/resumes%2F1754296141833_bayoresume.docx?alt=media&token=609f2f65-a36d-40e8-b833-3b2b3dc3a831",
    featured: false,
  },
  {
    id: "emmanuel-archibong",
    name: "Emmanuel Archibong",
    headline: "Graphic & Brand Designer · Logo & Visual Identity",
    bio: "Graphic designer with a passion for creating visual experiences that captivate and inspire. I believe design is not just about aesthetics, but also about solving problems and communicating messages effectively. Over the years I've honed a keen eye for detail, color, and composition.",
    location: "Lagos, Nigeria",
    country: "Nigeria",
    profilePhotoUrl: "https://res.cloudinary.com/dwwzrtzb8/image/upload/v1754239786/profile_images/IMG_20250620_021447_912.webp.webp",
    sectors: ["design_ux"],
    primarySkills: ["Brand Design", "Logo Design", "Graphic Design", "Visual Identity"],
    secondarySkills: ["Typography", "Color Theory", "Photography"],
    yearsOfExperience: 5,
    availability: "2 weeks",
    employmentType: ["Full-time", "Contract"],
    compensationMin: 800,
    compensationMax: 1400,
    portfolioLinks: {
      linkedin: "https://www.linkedin.com/in/kluas",
    },
    resumeUrl: "https://firebasestorage.googleapis.com/v0/b/mikeokpechi-e4331.firebasestorage.app/o/resumes%2F1754240529669_cv.pdf?alt=media&token=055cc3e4-177c-451c-b45c-fd7010bc72a7",
    featured: false,
  },
  {
    id: "daniel-okpechi",
    name: "Daniel C. Okpechi",
    headline: "Product Manager · FinTech, EdTech & SaaS",
    bio: "Product Manager with a strong technical background and over 3 years of experience leading end-to-end product development across FinTech, EdTech, and SaaS platforms. With a First-Class degree in Computer Science and nearly 4 years of experience as a Product Designer, I bring a hybrid mindset blending product strategy, UX, and technical understanding. Currently based in the UK.",
    location: "London, United Kingdom",
    country: "United Kingdom",
    profilePhotoUrl: "https://res.cloudinary.com/dwwzrtzb8/image/upload/v1754241463/profile_images/IMG_6511.jpeg.jpg",
    sectors: ["product_management", "design_ux"],
    primarySkills: ["Product Management", "Product Strategy", "UX Design", "Agile"],
    secondarySkills: ["Roadmap Planning", "Stakeholder Management", "Figma", "Mobile Development"],
    yearsOfExperience: 4,
    availability: "2 weeks",
    employmentType: ["Full-time"],
    compensationMin: 1200,
    compensationMax: 2000,
    portfolioLinks: {
      portfolio: "https://danielokpechi.netlify.app/",
      linkedin: "https://www.linkedin.com/in/danielokpechi",
    },
    resumeUrl: "https://firebasestorage.googleapis.com/v0/b/mikeokpechi-e4331.firebasestorage.app/o/resumes%2F1754241792265_Chinedum_Okpechi_CV%202.pdf?alt=media&token=f040ef1f-beec-487c-97dd-b251f8461261",
    featured: true,
  },
  {
    id: "chukwuebuka-felix-jibulu",
    name: "Chukwuebuka Felix Jibulu",
    headline: "Scrum Master & Business Analyst · 6 Years Experience",
    bio: "Committed and results-oriented certified Business Analyst and Scrum Master with 6+ years delivering high-impact digital solutions across tech and healthcare industries. Skilled in leading cross-functional Agile teams, gathering and translating complex business requirements into actionable roadmaps.",
    location: "Lagos, Nigeria",
    country: "Nigeria",
    profilePhotoUrl: "https://res.cloudinary.com/dwwzrtzb8/image/upload/v1754681329/profile_images/IMG_8637.jpeg.jpg",
    coverMediaUrl: "https://res.cloudinary.com/dwwzrtzb8/image/upload/v1754681347/profile_images/IMG_0268.jpeg.jpg",
    sectors: ["product_management"],
    primarySkills: ["Agile", "Scrum", "Business Analysis", "Stakeholder Management"],
    secondarySkills: ["Product Strategy", "Communication", "Team Leadership"],
    yearsOfExperience: 6,
    availability: "2 weeks",
    employmentType: ["Full-time", "Contract"],
    compensationMin: 1200,
    compensationMax: 2000,
    portfolioLinks: {
      linkedin: "https://www.linkedin.com/in/felix-jibulu-8344482a3",
    },
    resumeUrl: "https://firebasestorage.googleapis.com/v0/b/mikeokpechi-e4331.firebasestorage.app/o/resumes%2F1754681480185_Professional%20CV.pdf?alt=media&token=e3eedf2b-8100-4659-a1eb-7157df1b444c",
    featured: false,
  },
  {
    id: "rita-ehichioya",
    name: "Rita Ehichioya",
    headline: "Product Manager · Fintech, HRTech & Talent Platforms",
    bio: "Product Manager with expertise in product strategy, product lifecycle management, and cross-functional leadership. I've led end-to-end product development achieving 70% growth in user engagement, 40% faster loan recovery, and 35% reduction in approval time. I combine strategic vision with hands-on execution.",
    location: "Lagos, Nigeria",
    country: "Nigeria",
    profilePhotoUrl: "https://res.cloudinary.com/dwwzrtzb8/image/upload/v1755451050/profile_images/6.jpg.jpg",
    coverMediaUrl: "https://res.cloudinary.com/dwwzrtzb8/image/upload/v1755450979/profile_images/c678c0ef-4ca2-40c0-ac99-ad6fc7d9da3a.jpeg.jpg",
    sectors: ["product_management"],
    primarySkills: ["Product Strategy", "Product Roadmap", "Agile", "UX Design"],
    secondarySkills: ["Jira", "Figma", "A/B Testing", "User Research", "Data-Driven Decisions"],
    yearsOfExperience: 3,
    availability: "2 weeks",
    employmentType: ["Full-time", "Contract"],
    compensationMin: 900,
    compensationMax: 1600,
    portfolioLinks: {
      portfolio: "https://rita-ehichioya-portfolio.notion.site",
      linkedin: "https://www.linkedin.com/in/rita-ehichioya/",
    },
    resumeUrl: "https://firebasestorage.googleapis.com/v0/b/mikeokpechi-e4331.firebasestorage.app/o/resumes%2F1755452866583_Product%20Manager%20Resume%20Rita%20Ehichioya.pdf.pdf?alt=media&token=50ec17a2-9ce3-483e-9d75-8b9e942cb0f6",
    featured: false,
  },
  {
    id: "sunday-peace-christian",
    name: "Sunday Peace Christian",
    headline: "Product Manager · Logistics, Tech & Digital Services",
    bio: "Product Manager with hands-on experience guiding products from idea to delivery across logistics, tech hubs, and digital services. I've led cross-functional teams, written clear PRDs, built roadmaps, and turned research insights into real product improvements. My strength lies in creating clarity.",
    location: "Lagos, Nigeria",
    country: "Nigeria",
    profilePhotoUrl: "https://res.cloudinary.com/dwwzrtzb8/image/upload/v1754302190/profile_images/IMG_6105.jpeg.jpg",
    coverMediaUrl: "https://res.cloudinary.com/dwwzrtzb8/image/upload/v1754302214/profile_images/IMG_7489.jpeg.jpg",
    sectors: ["product_management"],
    primarySkills: ["Product Management", "Agile", "Roadmap Planning", "Jira"],
    secondarySkills: ["ClickUp", "Asana", "Trello", "Figma", "User Research", "Stakeholder Communication"],
    yearsOfExperience: 2,
    availability: "2 weeks",
    employmentType: ["Full-time", "Contract"],
    compensationMin: 700,
    compensationMax: 1200,
    portfolioLinks: {
      linkedin: "https://www.linkedin.com/in/peace-sunday",
    },
    resumeUrl: "https://firebasestorage.googleapis.com/v0/b/mikeokpechi-e4331.firebasestorage.app/o/resumes%2F1756406649774_Product%20Management%20Resume-Peace%20Sunday.pdf?alt=media&token=881232a1-25ef-4c1d-a007-e221ec7bc029",
    featured: false,
  },
  {
    id: "ezekiel-dada",
    name: "Ezekiel Dada",
    headline: "Product Manager · Healthtech, Fintech & SaaS",
    bio: "Product leader passionate about turning ideas into scalable, revenue-driving solutions. I've led cross-functional teams to launch AI-powered healthtech platforms, fintech payment solutions, and SaaS products — consistently delivering measurable results with +20% user satisfaction and +15% feature engagement.",
    location: "Lagos, Nigeria",
    country: "Nigeria",
    profilePhotoUrl: "https://res.cloudinary.com/dwwzrtzb8/image/upload/v1755437281/profile_images/WhatsApp%20Image%202025-08-09%20at%2009.41.59_8b435ee4.jpg.jpg",
    sectors: ["product_management"],
    primarySkills: ["Product Strategy", "Stakeholder Management", "Agile", "GTM Strategy"],
    secondarySkills: ["Jira", "Mixpanel", "Asana", "Notion", "API Testing"],
    yearsOfExperience: 3,
    availability: "2 weeks",
    employmentType: ["Full-time"],
    compensationMin: 900,
    compensationMax: 1500,
    portfolioLinks: {
      linkedin: "https://www.linkedin.com/in/ezekiel-dada-1b652a216/",
    },
    resumeUrl: "https://firebasestorage.googleapis.com/v0/b/mikeokpechi-e4331.firebasestorage.app/o/resumes%2FEzekiel%20Dada's%20Resume%203.pdf?alt=media&token=8605e5a7-f5dc-4453-9978-e42196a6d06c",
    featured: false,
  },
  {
    id: "gbeminiyi-olusanya",
    name: "Gbeminiyi Gbenga Olusanya",
    headline: "Product Manager · Operations, HR & Tech Community",
    bio: "Aspiring Product Manager with a toolkit built from experience in operations, HR, IT support, and web/app development. I've cut setup time by 20%, boosted on-time delivery from 75% to 95%, and coordinated feedback improving event satisfaction by 25%. I thrive in fast-moving environments where strategy meets execution.",
    location: "Lagos, Nigeria",
    country: "Nigeria",
    profilePhotoUrl: "https://res.cloudinary.com/dwwzrtzb8/image/upload/v1755285046/profile_images/IMG_3401.jpeg.jpg",
    sectors: ["product_management"],
    primarySkills: ["Product Management", "Agile", "Jira", "Figma"],
    secondarySkills: ["Trello", "Notion", "HTML", "CSS", "JavaScript", "Copywriting"],
    yearsOfExperience: 3,
    availability: "Immediate",
    employmentType: ["Full-time", "Contract"],
    compensationMin: 700,
    compensationMax: 1200,
    portfolioLinks: {
      github: "https://github.com/gbeminiyigbenga",
      linkedin: "https://www.linkedin.com/in/gbeminiyi-gbenga-olusanya-1b8338229",
    },
    resumeUrl: "https://firebasestorage.googleapis.com/v0/b/mikeokpechi-e4331.firebasestorage.app/o/resumes%2F1755285507743_GBEMINIYI%20OLUSANYA%20RESUME%20PM.pdf?alt=media&token=03ece97b-b9e6-4440-821c-a31c00447294",
    featured: false,
  },
  {
    id: "elizabeth-rotimi",
    name: "Elizabeth Rotimi",
    headline: "Technical Product Manager · Operations & QA",
    bio: "A technical product manager that loves to solve problems. Brings together deep product thinking with hands-on quality assurance and operations experience to deliver software people can trust.",
    location: "Lagos, Nigeria",
    country: "Nigeria",
    profilePhotoUrl: "https://res.cloudinary.com/dwwzrtzb8/image/upload/v1754548680/profile_images/IMG_9868.jpeg.jpg",
    coverMediaUrl: "https://res.cloudinary.com/dwwzrtzb8/image/upload/v1754252186/profile_images/6b282a31-9bb4-4541-a270-101c4005b24a.jpeg.jpg",
    sectors: ["product_management"],
    primarySkills: ["Product Management", "QA Testing", "Technical Writing", "Operations"],
    secondarySkills: ["Stakeholder Communication", "People Operations"],
    yearsOfExperience: 2,
    availability: "2 weeks",
    employmentType: ["Full-time", "Contract"],
    compensationMin: 600,
    compensationMax: 1100,
    portfolioLinks: {
      linkedin: "https://www.linkedin.com/in/elizabeth-boluwatife-rotimi",
    },
    resumeUrl: "https://firebasestorage.googleapis.com/v0/b/mikeokpechi-e4331.firebasestorage.app/o/resumes%2F1754548932762_Boluwatife%20Rotimi.pdf?alt=media&token=a11ed730-6ca6-4e46-92f9-d3ae643df24a",
    featured: false,
  },
  {
    id: "christian-edward-ngwu",
    name: "Christian Edward-Ngwu",
    headline: "Marketing Executive & Brand Strategist · Founder of Novalith",
    bio: "Marketing executive, brand strategist, and founder of Novalith Marketing. Over the years, I've worked with startups, SMEs, and established brands delivering measurable growth through creative campaigns, emotional marketing, and data-driven strategies. My approach blends creativity with business intelligence.",
    location: "Lagos, Nigeria",
    country: "Nigeria",
    profilePhotoUrl: "https://res.cloudinary.com/dwwzrtzb8/image/upload/v1754668759/profile_images/%40chryzthegenie%20-%20R%E2%A4%93Download_Original.jpeg.jpg",
    coverMediaUrl: "https://res.cloudinary.com/dwwzrtzb8/image/upload/v1754668786/profile_images/b748e493-21eb-4d64-8dfa-0dc18df32552_Original.jpeg.jpg",
    sectors: ["marketing"],
    primarySkills: ["Brand Strategy", "Social Media Marketing", "Content Creation", "Paid Ads"],
    secondarySkills: ["Creative Campaign Development", "Client Relations", "Market Research", "Project Management"],
    yearsOfExperience: 5,
    availability: "2 weeks",
    employmentType: ["Full-time", "Contract"],
    compensationMin: 900,
    compensationMax: 1600,
    portfolioLinks: {
      portfolio: "https://linktr.ee/thechristian.en",
      linkedin: "https://www.linkedin.com/in/christianedward-ngwu",
    },
    resumeUrl: "https://firebasestorage.googleapis.com/v0/b/mikeokpechi-e4331.firebasestorage.app/o/resumes%2F1754669327152_Novalith%20Marketing%20Portfolio%202025.pdf?alt=media&token=e9994b5c-029b-4fef-b2df-decc3a571528",
    featured: true,
  },
  {
    id: "anthony-ibazebo",
    name: "Anthony Eromosele Ibazebo",
    headline: "Social Media Manager & Content Strategist",
    bio: "Creative and results-driven Social Media Manager and Content Strategist with 1+ year of experience building personal brands, managing campaigns, and writing for digital platforms. Currently leading paid ads and media buying at a marketing agency. Strong digital and analytical skills.",
    location: "Lagos, Nigeria",
    country: "Nigeria",
    profilePhotoUrl: "https://res.cloudinary.com/dwwzrtzb8/image/upload/v1754252862/profile_images/Anthony-Passport.jpg.jpg",
    coverMediaUrl: "https://res.cloudinary.com/dwwzrtzb8/image/upload/v1754252882/profile_images/DSC_0551.jpg.jpg",
    sectors: ["marketing"],
    primarySkills: ["Social Media Strategy", "Content Creation", "Paid Ads (Meta & Google)", "Copywriting"],
    secondarySkills: ["Community Management", "Analytics", "Scriptwriting", "Admin Support"],
    yearsOfExperience: 2,
    availability: "2 weeks",
    employmentType: ["Full-time", "Contract"],
    compensationMin: 500,
    compensationMax: 900,
    portfolioLinks: {
      linkedin: "https://www.linkedin.com/in/ibazebotony",
    },
    resumeUrl: "https://firebasestorage.googleapis.com/v0/b/mikeokpechi-e4331.firebasestorage.app/o/resumes%2F1754305469763_Anthony%20Ibazebo%20Work%20Resume.pdf?alt=media&token=d6c09761-a042-40ce-9455-9b43844e6ec5",
    featured: false,
  },
  {
    id: "menewe-favour",
    name: "Menewe Favour Akpeweoghene",
    headline: "Social Media Manager & Content Creator · YouTuber",
    bio: "Creative social media manager, content creator, and YouTuber with a strong foundation in Nutrition & Dietetics. I manage social media across Instagram, TikTok, X, and Facebook — planning and scheduling content, developing strategies, writing scripts, and tracking performance. I also run a personal YouTube channel focused on storytelling around student life.",
    location: "Lagos, Nigeria",
    country: "Nigeria",
    profilePhotoUrl: "https://res.cloudinary.com/dwwzrtzb8/image/upload/v1754175027/profile_images/612150e5-06d6-4a6b-af19-5bbd7e94f950.jpeg.jpg",
    sectors: ["marketing"],
    primarySkills: ["Social Media Management", "Content Creation", "Storytelling", "Video Production"],
    secondarySkills: ["Instagram", "TikTok", "YouTube", "Community Building"],
    yearsOfExperience: 3,
    availability: "2 weeks",
    employmentType: ["Full-time", "Contract", "Part-time"],
    compensationMin: 500,
    compensationMax: 900,
    portfolioLinks: {
      linkedin: "https://www.linkedin.com/in/favour-menewe-871b33288",
    },
    resumeUrl: "https://firebasestorage.googleapis.com/v0/b/mikeokpechi-e4331.firebasestorage.app/o/resumes%2F1754174967646_Menewe%20Favour%20Resume.pdf.pdf?alt=media&token=61aceb53-2322-4250-8973-8ebb8c2d398a",
    featured: false,
  },
  {
    id: "jesuloba-omolaja",
    name: "Jesuloba Omolaja",
    headline: "Content Writer & UX Copywriter · Strategy & Story",
    bio: "Content writer and UX copywriter who sits at the intersection of strategy, story, and soul. With over two years of experience writing for digital products, podcasts, and purpose-driven communities, I specialize in turning ideas into words that feel clear, human, and intentional.",
    location: "Lagos, Nigeria",
    country: "Nigeria",
    profilePhotoUrl: "https://res.cloudinary.com/dwwzrtzb8/image/upload/v1755089061/profile_images/E00C0FA5-9BD4-429E-B61E-3128451E13DD.png.png",
    sectors: ["marketing"],
    primarySkills: ["Content Writing", "UX Copywriting", "Brand Voice", "Storytelling"],
    secondarySkills: ["Google Docs", "Notion", "Canva", "Script Writing"],
    yearsOfExperience: 2,
    availability: "Immediate",
    employmentType: ["Full-time", "Contract", "Part-time"],
    compensationMin: 500,
    compensationMax: 900,
    portfolioLinks: {
      linkedin: "https://www.linkedin.com/in/jesuloba-omolaja-963112288",
    },
    resumeUrl: "https://firebasestorage.googleapis.com/v0/b/mikeokpechi-e4331.firebasestorage.app/o/resumes%2F1755088979194_%20OMOLAJA%20JESULOBA%20%7C%20UX%20Writer%20.pdf?alt=media&token=3bbbefe6-dad9-40ed-8a42-492ea46c3abc",
    featured: false,
  },
  {
    id: "akinduro-folasade",
    name: "Akinduro Folasade",
    headline: "Quality Assurance Engineer · Manual & Automation Testing",
    bio: "QA Engineer with a BSc in Software Engineering with First Class Honours. Hands-on experience in manual and automation testing, creating and executing detailed test plans, designing test cases, and performing functional, regression, performance, usability, and exploratory testing. My technical background in frontend development enables me to bridge the gap between development and QA.",
    location: "Lagos, Nigeria",
    country: "Nigeria",
    profilePhotoUrl: "https://res.cloudinary.com/dwwzrtzb8/image/upload/v1755176625/profile_images/IMG_8377.jpeg.jpg",
    sectors: ["software_engineering"],
    primarySkills: ["Manual Testing", "Automation Testing (Selenium)", "Playwright", "API Testing"],
    secondarySkills: ["Jira", "ClickUp", "Test Case Design", "Postman", "React", "Performance Testing"],
    yearsOfExperience: 1,
    availability: "2 weeks",
    employmentType: ["Full-time", "Contract"],
    compensationMin: 500,
    compensationMax: 900,
    portfolioLinks: {
      linkedin: "https://www.linkedin.com/in/akinduro-folake-7125862b6",
    },
    resumeUrl: "https://firebasestorage.googleapis.com/v0/b/mikeokpechi-e4331.firebasestorage.app/o/resumes%2F1755253150319_Akinduro-Folasade-Folake-current%20resume%20.pdf?alt=media&token=72844bfc-7e76-4728-8255-ef675574babc",
    featured: false,
  },
  {
    id: "ngene-michael",
    name: "Ngene Michael",
    headline: "Flutter Developer · Mobile UI/UX & Cross-Platform Apps",
    bio: "Skilled Flutter developer passionate about building beautiful, high-performance mobile apps. He combines clean code practices with creative UI/UX design to deliver engaging user experiences across Android and iOS.",
    location: "Lagos, Nigeria",
    country: "Nigeria",
    profilePhotoUrl: "https://res.cloudinary.com/dwwzrtzb8/image/upload/v1754731480/profile_images/IMG_8879.jpeg.jpg",
    coverMediaUrl: "https://res.cloudinary.com/dwwzrtzb8/image/upload/v1754731515/profile_images/IMG_5313.jpeg.jpg",
    sectors: ["mobile_development"],
    primarySkills: ["Flutter", "Dart", "Mobile UI/UX", "Firebase"],
    secondarySkills: ["Android", "iOS", "REST APIs"],
    yearsOfExperience: 5,
    availability: "2 weeks",
    employmentType: ["Full-time"],
    compensationMin: 1000,
    compensationMax: 1700,
    portfolioLinks: {
      linkedin: "https://www.linkedin.com/in/michael-ngene-mmba-043361205",
    },
    resumeUrl: "https://firebasestorage.googleapis.com/v0/b/mikeokpechi-e4331.firebasestorage.app/o/resumes%2F1754733255550_Ngene%20Michael%20O%20-%20Mobile%20App%20Developer.pdf?alt=media&token=2eb86e6a-532e-418e-b95e-8dff502f6e81",
    featured: true,
  },
  {
    id: "joemdjossou",
    name: "Y. Emmanuel Josué Djossou",
    headline: "Mobile Engineer · Flutter, Firebase & Technical Writing",
    bio: "Bilingual Flutter developer fluent in French and English, with 5+ years of experience building high-performance cross-platform apps for iOS and Android. I've worked on impactful projects including e-commerce and influencer marketing apps, integrating Firebase, APIs, Google Maps, and advanced state management.",
    location: "Cotonou, Benin",
    country: "Benin",
    profilePhotoUrl: "https://res.cloudinary.com/dwwzrtzb8/image/upload/v1754995384/profile_images/IMG_2483.jpeg.jpg",
    coverMediaUrl: "https://res.cloudinary.com/dwwzrtzb8/image/upload/v1754310777/profile_images/IMG_6271.jpeg.jpg",
    sectors: ["mobile_development", "software_engineering"],
    primarySkills: ["Flutter", "Dart", "Firebase", "Mobile Development"],
    secondarySkills: ["Technical Writing", "Public Speaking", "Leadership", "State Management"],
    yearsOfExperience: 4,
    availability: "2 weeks",
    employmentType: ["Full-time", "Contract"],
    compensationMin: 1000,
    compensationMax: 1700,
    portfolioLinks: {
      github: "https://github.com/joemdjossou",
      linkedin: "https://www.linkedin.com/in/joemdjossou",
    },
    resumeUrl: "https://firebasestorage.googleapis.com/v0/b/mikeokpechi-e4331.firebasestorage.app/o/resumes%2F1754996209344_Josue_Djossou_Resume.pdf?alt=media&token=77589623-13a5-47c1-90d1-41effebff517",
    featured: false,
  },
  {
    id: "chima-okwuokei",
    name: "Chima Stanislaus Okwuokei",
    headline: "Frontend & AI Developer · React & Machine Learning",
    bio: "Intelligent, hardworking, and self-motivated problem solver with great interest in the fields of Artificial Intelligence and Software Engineering. I combine frontend skills with AI development to build smarter, more adaptive interfaces.",
    location: "Lagos, Nigeria",
    country: "Nigeria",
    profilePhotoUrl: "https://res.cloudinary.com/dwwzrtzb8/image/upload/v1754906403/profile_images/IMG_20231225_211622_845.jpg.jpg",
    sectors: ["web_development", "ai_ml"],
    primarySkills: ["React", "JavaScript", "Machine Learning", "Python"],
    secondarySkills: ["TypeScript", "AI Development", "REST APIs"],
    yearsOfExperience: 2,
    availability: "Immediate",
    employmentType: ["Full-time", "Contract"],
    compensationMin: 600,
    compensationMax: 1000,
    portfolioLinks: {
      linkedin: "https://www.linkedin.com/in/chima-okwuokei-59783425b/",
    },
    resumeUrl: "https://firebasestorage.googleapis.com/v0/b/mikeokpechi-e4331.firebasestorage.app/o/resumes%2F1754906786675_CHIMA%20STANISLAUS%20OKWUOKEI%20RESUME-1(1)-2.pdf?alt=media&token=f15bae90-f042-4873-a328-6aeb4fa2b455",
    featured: false,
  },
  {
    id: "olamoyegun-ayomide",
    name: "Olamoyegun Ayomide Oluwamayowa",
    headline: "Backend Developer · Python, C# & ASP.NET",
    bio: "Backend Developer with a First-Class degree in Software Engineering and a strong foundation in building scalable, efficient systems. I've worked on diverse projects — from chatbots and internal tools to APIs and backend features — using technologies like Python, C#, Flask, and ASP.NET. I enjoy building solutions that are clean under the hood and meaningful in impact.",
    location: "Lagos, Nigeria",
    country: "Nigeria",
    profilePhotoUrl: "https://res.cloudinary.com/dwwzrtzb8/image/upload/v1754491431/profile_images/ayo.png.png",
    sectors: ["software_engineering", "ai_ml"],
    primarySkills: ["Python", "C#", "Flask", "ASP.NET Core"],
    secondarySkills: ["WordPress", "SQLite", "MySQL", "MSSQL", "NLP"],
    yearsOfExperience: 2,
    availability: "2 weeks",
    employmentType: ["Full-time", "Contract"],
    compensationMin: 600,
    compensationMax: 1100,
    portfolioLinks: {
      github: "https://github.com/OlamoyegunAyomide",
      linkedin: "https://www.linkedin.com/in/ayomide-olamoyegun/",
    },
    resumeUrl: "https://firebasestorage.googleapis.com/v0/b/mikeokpechi-e4331.firebasestorage.app/o/resumes%2F1754490353805_Olamoyegun%20Ayomide's%20Professional%20CV.pdf?alt=media&token=a55c7d8c-7333-45fd-9b7b-56be8e37bc81",
    featured: false,
  },
  {
    id: "egwuatu-chioma",
    name: "Egwuatu Chioma Mary",
    headline: "Virtual Assistant & Operations Manager · Public Health Background",
    bio: "Recent graduate of Babcock University with a 2.1 BSc in Public Health. Public health consultant/researcher, virtual assistant, and operations manager. Open to remote and international opportunities.",
    location: "Lagos, Nigeria",
    country: "Nigeria",
    profilePhotoUrl: "https://res.cloudinary.com/dwwzrtzb8/image/upload/v1754661173/profile_images/IMG_5388.jpeg.jpg",
    coverMediaUrl: "https://res.cloudinary.com/dwwzrtzb8/image/upload/v1754661938/profile_images/IMG_3179.jpeg.jpg",
    sectors: ["product_management"],
    primarySkills: ["Operations Management", "Virtual Assistance", "Leadership", "Time Management"],
    secondarySkills: ["Public Health", "Research", "Task Prioritization"],
    yearsOfExperience: 2,
    availability: "Immediate",
    employmentType: ["Full-time", "Contract", "Part-time"],
    compensationMin: 400,
    compensationMax: 800,
    portfolioLinks: {
      linkedin: "https://www.linkedin.com/in/egwuatu-chioma-a51254314",
    },
    resumeUrl: "https://firebasestorage.googleapis.com/v0/b/mikeokpechi-e4331.firebasestorage.app/o/resumes%2F1754661510109_Egwuatu%20chioma%20glyde%20cv.pdf?alt=media&token=ec39c7b6-f4c9-49c1-8f8d-1e099519b9b3",
    featured: false,
  },
  {
    id: "gift-ndoma",
    name: "Gift Ndoma",
    headline: "Frontend Developer · HTML, CSS, JavaScript & C#",
    bio: "Software Development student at BYU-Idaho, passionate about continuous learning, embracing challenges, and personal growth. I enjoy exploring new ideas and developing skills that prepare me to make a positive impact.",
    location: "Rexburg, United States",
    country: "United States",
    profilePhotoUrl: "https://res.cloudinary.com/dwwzrtzb8/image/upload/v1755378790/profile_images/profile-2.jpeg.jpg",
    coverMediaUrl: "https://res.cloudinary.com/dwwzrtzb8/image/upload/v1755378829/profile_images/favorite.jpg.jpg",
    sectors: ["web_development"],
    primarySkills: ["HTML", "CSS", "JavaScript", "C#"],
    secondarySkills: ["Responsive Web Design", "SEO Basics", "OOP", "Problem-Solving"],
    yearsOfExperience: 1,
    availability: "Immediate",
    employmentType: ["Full-time", "Contract", "Part-time"],
    compensationMin: 400,
    compensationMax: 700,
    portfolioLinks: {
      github: "https://github.com/gift-ndoma",
      linkedin: "https://www.linkedin.com/in/gift-ndoma-59a9a82a8/",
    },
    resumeUrl: "https://firebasestorage.googleapis.com/v0/b/mikeokpechi-e4331.firebasestorage.app/o/resumes%2F1755379746239_Gift%20Ndoma%20-%20Resume(2).pdf?alt=media&token=7291dc1d-4f4c-4952-b2ae-559f71b6c584",
    featured: false,
  },
];

export interface SavedFolder {
  id: string;
  name: string;
  candidates: TalentProfile[];
}

export const mockSavedFolders: SavedFolder[] = [
  { id: "frontend-shortlist", name: "Frontend Shortlist", candidates: [] },
  { id: "interviewed", name: "Interviewed", candidates: [] },
  { id: "offer-pending", name: "Offer Pending", candidates: [] },
];
